name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Create env file
        run: |
          echo "REACT_APP_TOSS_PAYMENTS_SECRET_KEY=${{ secrets.REACT_APP_TOSS_PAYMENTS_SECRET_KEY }}" >> .env
          echo "REACT_APP_TOSS_PAYMENTS_CLIENT_KEY=${{ secrets.REACT_APP_TOSS_PAYMENTS_CLIENT_KEY }}" >> .env
          echo "REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}" >> .env
          echo "REACT_APP_API_URL_DEV=${{ secrets.REACT_APP_API_URL_DEV }}" >> .env
          echo "REACT_APP_API_URL_PROD=${{ secrets.REACT_APP_API_URL_PROD }}" >> .env
          echo "REACT_APP_CLIENT_URL=${{ secrets.REACT_APP_CLIENT_URL }}" >> .env
          echo "REACT_APP_CALLBACK_URL=${{ secrets.REACT_APP_CALLBACK_URL }}" >> .env
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env

      - name: Build
        run: npm run build

      # .nojekyll 파일 생성 (중요!)
      - name: Create .nojekyll file
        run: touch build/.nojekyll

      # 404.html 파일 생성
      - name: Create 404.html for SPA routing
        run: |
          if [ -f build/index.html ]; then
            cp build/index.html build/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: www.xn--vb0b67vepvv2b.com
          force_orphan: true # gh-pages 브랜치를 완전히 초기화
